trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Azure-Terraform-Details

stages:
- stage: Build_Image
  jobs:
  - job:
    steps:
    - task: Docker@0
      displayName: 'Build an image'
      inputs:
        azureSubscription: '$(subscription-name)'
        azureContainerRegistry: '$(acr-details)'
        includeLatestTag: true

    - task: Docker@0
      displayName: 'Push an image'
      inputs:
        azureSubscription: '$(subscription-name)'
        azureContainerRegistry: '$(acr-details)'
        includeLatestTag: true
        action: 'Push an image'

- stage: Update_WebApp
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      displayName: 'Update webapp image'
      inputs:
        azureSubscription: '$(subscription-name)'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config container set --docker-custom-image-name "DOCKER|serviantechtaskcr.azurecr.io/jleruohep/techchallengeapp:$(Build.BuildId)" --docker-registry-server-url "https://serviantechtaskcr.azurecr.io" --docker-registry-server-user serviantechtaskcr --name servian-techtask-appservice --resource-group servian-techtask
          az webapp config set --name servian-techtask-appservice --resource-group servian-techtask --startup-file serve