trigger: none
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Azure-Terraform-Details

steps:
- task: GoTool@0
  displayName: 'Use Go 1.15'
  inputs:
    version: 1.15

- task: TerraformInstaller@0
  displayName: 'Use Terraform 0.12.29'
  inputs:
    terraformVersion: '0.12.29'

- task: Go@0
  displayName: 'go test'
  inputs:
    command: test

- task: TerraformTaskV1@0
  displayName: 'Terraform : Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    backendServiceArm: '$(subscription-name)'
    backendAzureRmResourceGroupName: 'terraformstate'
    backendAzureRmStorageAccountName: 'mkservianterraformstate'
    backendAzureRmContainerName: 'servian-techtask'
    backendAzureRmKey: 'servian-techtask'

- task: TerraformTaskV1@0
  displayName: 'Terraform : Validate'
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'

